language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install responses
  - pip install coveralls

# command to run tests
script:
  - coverage run AcsClientTestCase.py
  - coveralls